# Generated by Django 2.1.3 on 2021-05-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='model',
            name='model_description',
            field=models.CharField(default=False, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_name',
            field=models.CharField(default=False, max_length=128),
        ),
    ]
