# Generated by Django 2.1.3 on 2019-04-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model_creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
