# Generated by Django 2.1.3 on 2019-04-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_auto_20190420_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model_benign_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_malicious_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
