# Generated by Django 2.1.3 on 2019-04-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_auto_20190420_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='fqdninstance',
            name='fqdn_score',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='fqdninstance',
            name='fqdn_type',
            field=models.CharField(choices=[('m', 'Malicious'), ('b', 'Benign'), ('u', 'Unknown')], default='u', max_length=25),
        ),
        migrations.AlterField(
            model_name='fqdninstance',
            name='brand_domain_match',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='fqdninstance',
            name='brand_subdomain_match',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='fqdninstance',
            name='fqdn_domain',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fqdninstance',
            name='fqdn_subdomain',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
