# Generated by Django 2.1.3 on 2019-04-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_auto_20190421_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fqdninstance',
            name='fqdn',
        ),
        migrations.AddField(
            model_name='fqdninstance',
            name='fqdn_full',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
