# Generated by Django 2.1.3 on 2019-04-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0007_auto_20190421_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fqdninstance',
            name='fqdn_keywords',
        ),
        migrations.RemoveField(
            model_name='fqdninstance',
            name='fqdn_tags',
        ),
        migrations.RemoveField(
            model_name='fqdninstance',
            name='match_tlds',
        ),
        migrations.AlterField(
            model_name='fqdninstance',
            name='entropy',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='fqdninstance',
            name='fqdn_type',
            field=models.CharField(choices=[('m', 'Malicious'), ('b', 'Benign'), ('u', 'Unknown')], default='u', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='fqdninstance',
            name='model_match',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
