# Generated by Django 2.1.3 on 2019-04-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0008_auto_20190421_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='fqdninstance',
            name='fqdn_tested',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
