# Generated by Django 2.1.3 on 2019-04-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0010_auto_20190424_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fqdninstance',
            name='brand_match',
            field=models.ManyToManyField(null=True, to='trainer.Brand'),
        ),
    ]
