# Generated by Django 2.1.3 on 2019-04-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0011_auto_20190424_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fqdninstance',
            old_name='fqdn_score',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='model',
            name='confusion_matrix',
        ),
        migrations.AddField(
            model_name='fqdninstance',
            name='date_seen',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='fqdninstance',
            name='keyword_match',
            field=models.ManyToManyField(to='trainer.KeyWord'),
        ),
        migrations.AddField(
            model_name='model',
            name='accuracy_precision',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='accuracy_recall',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='fqdninstance',
            name='brand_match',
            field=models.ManyToManyField(to='trainer.Brand'),
        ),
    ]
