# Generated by Django 2.1.3 on 2019-04-25 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0012_auto_20190425_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='accuracty_test_set',
            new_name='accuracy_test_set',
        ),
    ]
