# Generated by Django 2.1.3 on 2019-04-25 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0013_auto_20190425_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='accuracy_confusion_matrix',
        ),
    ]
