# Generated by Django 2.1.3 on 2019-04-25 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0014_remove_model_accuracy_confusion_matrix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fqdninstance',
            name='brand_match',
        ),
        migrations.AddField(
            model_name='fqdninstance',
            name='brand_match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainer.Brand'),
        ),
        migrations.RemoveField(
            model_name='fqdninstance',
            name='keyword_match',
        ),
        migrations.AddField(
            model_name='fqdninstance',
            name='keyword_match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainer.KeyWord'),
        ),
    ]
