# Generated by Django 2.1.3 on 2019-05-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0015_auto_20190425_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fqdninstance',
            name='fqdn_type',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
