# Generated by Django 2.1.3 on 2019-05-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0016_auto_20190505_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='model_running',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
