# Generated by Django 2.1.3 on 2019-07-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0017_model_model_running'),
    ]

    operations = [
        migrations.CreateModel(
            name='training_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_set_name', models.CharField(default='Not Set', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='training_set',
            field=models.ManyToManyField(to='trainer.training_set'),
        ),
        migrations.AddField(
            model_name='domainprefix',
            name='training_set',
            field=models.ManyToManyField(to='trainer.training_set'),
        ),
        migrations.AddField(
            model_name='fqdn',
            name='training_set',
            field=models.ManyToManyField(to='trainer.training_set'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='training_set',
            field=models.ManyToManyField(to='trainer.training_set'),
        ),
        migrations.AddField(
            model_name='squatedword',
            name='training_set',
            field=models.ManyToManyField(to='trainer.training_set'),
        ),
        migrations.AddField(
            model_name='tag',
            name='training_set',
            field=models.ManyToManyField(to='trainer.training_set'),
        ),
        migrations.AddField(
            model_name='topleveldomain',
            name='training_set',
            field=models.ManyToManyField(to='trainer.training_set'),
        ),
    ]
