# Generated by Django 2.1.3 on 2019-07-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0018_auto_20190712_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='training_set',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to='trainer.training_set'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='training_set',
            field=models.ManyToManyField(default=1, to='trainer.training_set'),
        ),
    ]
