# Generated by Django 2.1.3 on 2019-07-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0019_auto_20190712_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='training_set',
            field=models.ManyToManyField(default=1, to='trainer.training_set'),
        ),
        migrations.AlterField(
            model_name='domainprefix',
            name='training_set',
            field=models.ManyToManyField(default=1, to='trainer.training_set'),
        ),
        migrations.AlterField(
            model_name='fqdn',
            name='training_set',
            field=models.ManyToManyField(default=1, to='trainer.training_set'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='training_set',
            field=models.ManyToManyField(default=1, to='trainer.training_set'),
        ),
        migrations.AlterField(
            model_name='squatedword',
            name='training_set',
            field=models.ManyToManyField(default=1, to='trainer.training_set'),
        ),
        migrations.AlterField(
            model_name='topleveldomain',
            name='training_set',
            field=models.ManyToManyField(default=1, to='trainer.training_set'),
        ),
    ]
