# Generated by Django 2.1.3 on 2019-07-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0021_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fqdninstance',
            name='brand_match',
        ),
        migrations.RemoveField(
            model_name='fqdninstance',
            name='keyword_match',
        ),
        migrations.AddField(
            model_name='fqdninstance',
            name='matched_brands',
            field=models.ForeignKey(null=True, on_delete=models.SET(1), to='trainer.Brand'),
        ),
        migrations.AddField(
            model_name='fqdninstance',
            name='matched_keywords',
            field=models.ForeignKey(null=True, on_delete=models.SET(1), to='trainer.KeyWord'),
        ),
    ]
