# Generated by Django 2.1.3 on 2019-07-14 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0022_auto_20190713_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='training_set',
        ),
        migrations.RemoveField(
            model_name='domainprefix',
            name='training_set',
        ),
        migrations.RemoveField(
            model_name='fqdn',
            name='training_set',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='training_set',
        ),
        migrations.RemoveField(
            model_name='model',
            name='training_set',
        ),
        migrations.RemoveField(
            model_name='squatedword',
            name='training_set',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='training_set',
        ),
        migrations.RemoveField(
            model_name='topleveldomain',
            name='training_set',
        ),
        migrations.DeleteModel(
            name='training_set',
        ),
    ]
