# Generated by Django 2.1.3 on 2019-07-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0023_auto_20190713_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fqdninstance',
            name='matched_brands',
        ),
        migrations.AddField(
            model_name='fqdninstance',
            name='matched_brands',
            field=models.ManyToManyField(to='trainer.Brand'),
        ),
        migrations.RemoveField(
            model_name='fqdninstance',
            name='matched_keywords',
        ),
        migrations.AddField(
            model_name='fqdninstance',
            name='matched_keywords',
            field=models.ManyToManyField(to='trainer.KeyWord'),
        ),
    ]
