# Generated by Django 2.2 on 2021-05-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelerTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, max_length=30, null=True)),
                ('task', models.BinaryField(null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('model_id', models.IntegerField(null=True)),
            ],
        ),
    ]
