# Generated by Django 2.1.3 on 2019-08-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertStreamTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, max_length=30, null=True)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
